## dynamic configuration ##

http:
    routers:
      routerTest:
        service: srv-grpc # required
        # rule is required
        rule: HostRegexp(`{.*}`) # -> any host
  
    services:
      srv-grpc:
        loadBalancer:
          servers:
          - url: h2c://localhost:9090 # using explicit `grpc://` protocol name is not allowed. Error:  Received http2 header with status: 500