## dynamic configuration ##
#  TODO
entryPoints:
  web:
    address: :8081
api: {}

http:
    routers:
      routerTest:
        service: srv-grpc
        rule: Host(`frontend.local`)
  
    services:
      srv-grpc:
        loadBalancer:
          servers:
          - url: grpc://localhost:9090